#!/bin/bash

echo "ℹ️ DOCKER_HOST=$DOCKER_HOST"
echo "ℹ️ PODMAN_COMPOSE_PROVIDER=$PODMAN_COMPOSE_PROVIDER"
echo "ℹ️ USER_NAME=$USER_NAME"
echo "ℹ️ ENV_FILE_PATH=$ENV_FILE_PATH"
echo "ℹ️ PROJECT_FILE_PATH=$PROJECT_FILE_PATH"
echo "ℹ️ PODMAN_FILE_PATH=$PODMAN_FILE_PATH"
echo "ℹ️ COMPOSE_ARGS=$1"

# Start the containers using podman-docker with docker-compose
sudo  \
	--preserve-env=DOCKER_HOST,PODMAN_COMPOSE_PROVIDER,USER_NAME,ENV_FILE_PATH,PROJECT_FILE_PATH   \
	-u $USER_NAME  \
	$PODMAN_FILE_PATH compose -f $PROJECT_FILE_PATH --env-file $ENV_FILE_PATH $1
