services:
  pgadmin:
    # image: dpage/pgadmin4
    build:
      context: ./src/pgadmin
      args:
        NETWORK: ${NETWORK}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    environment:
        PGADMIN_LISTEN_PORT: 80
    ports:
        - "${PGADMIN_PORT:-5050}:80"
    volumes:
        - pgadmin-data:/var/lib/pgadmin
    depends_on:
      postgress:
        condition: service_healthy

volumes:
  pgadmin-data: