services:
  swagger:
    image: swaggerapi/swagger-ui
    restart: always
    depends_on:
      postgress:
        condition: service_healthy
    ports:
      - "${SWAGGER_PORT:-8080}:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://127.0.0.1:${POSTGREST_PORT}/